name: hello world
on: [push]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Crear clave SSH
        env:
          ssh_keys: ${{secrets.SSH_KEY}}
        run:
          echo "$ssh_key" > key.pem
          chmod 600 key.pem
    
      - name: SSH Conection
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: ls

      